kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster1
nodes:
  - role: control-plane
    image: kindest/node:v1.24.15
    extraPortMappings:
      - containerPort: 6443
        hostPort: 36443  #安全组开放
        protocol: tcp
    extraMounts:
      - hostPath: /root/kind/node1-1
        containerPath: /files
  - role: worker
    image: kindest/node:v1.24.15
    extraPortMappings:
      - containerPort: 80
        hostPort: 30080
        protocol: tcp
      - containerPort: 443
        hostPort: 30443
        protocol: tcp
    labels:
      gateway: true
    extraMounts:
      - hostPath: /root/kind/node1-2
        containerPath: /files
  - role: worker
    image: kindest/node:v1.24.15
    extraMounts:
      - hostPath: /root/kind/node1-3
        containerPath: /files
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  podSubnet: "10.6.0.0/16" #自定义 pod IP 地址范围
  serviceSubnet: "10.96.0.0/16"
  kubeProxyMode: "ipvs"
