apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxapp
  namespace: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxapp
  template:
    metadata:
      labels:
        app: nginxapp
    spec:
      containers:
        - name: nginxapp
          image: nginx:1.18-alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxappsvc
  namespace: myweb
spec:
  selector:
    app: nginxapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
