apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.10.0
  name: kube-state-metrics
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    # 端口映设：注意如果使用 kind 部署测试，如果集群启动时，没有开放docker映射，
    # 需要使用 kube port-forward 完成端口转发
    # kubectl port-forward services/kube-state-metrics -n  kube-system  38080:8080 --address 0.0.0.0
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
    - name: telemetry
      port: 8081
      targetPort: telemetry
  selector:
    app.kubernetes.io/name: kube-state-metrics