apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  # 关连的 ServiceMonitor 选择器
  serviceMonitorSelector:
    # 注意此 label
    matchLabels:
      team: myweb
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  # 端口映设：注意如果使用 kind 部署测试，如果集群启动时，没有开放docker映射，
  # 需要使用 kube port-forward 完成端口转发
  # kubectl port-forward services/prometheus  39090:9090 --address 0.0.0.0
  ports:
    - name: web
      nodePort: 30900
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: prometheus