# 创建 kind 可使用的配置范例
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-test
nodes:
  # 一个控制面 node
- role: control-plane
  image: kindest/node:v1.20.15
  # 两个数据面 node
- role: worker
  image: kindest/node:v1.20.15
  extraPortMappings:   # 将 node 的端口映射到主机
  - containerPort: 30009
    hostPort: 30009
    protocol: tcp
  - containerPort: 6443
    hostPort: 36443
    protocol: tcp
- role: worker
  image: kindest/node:v1.20.15
#  extraMounts:  //挂载
#  - hostPath: /path/to/my/files/
#    containerPath: /files
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16" # 自定义 pod IP 地址范围
  serviceSubnet: "10.96.0.0/12" 
  kubeProxyMode: "ipvs"
