apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  templates:
    # 一个模版, 可以想成是一个 pod 任务
    - name: echo
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:3.12
        command: [echo, "{{inputs.parameters.message}}"]
    # 如果有任务依赖性，可以使用 dag 有向无环图执行
    - name: diamond
      dag:
        tasks:
          - name: A
            template: echo
            arguments:
              parameters: [{name: message, value: A}]
          - name: B
            dependencies: [A]
            template: echo
            arguments:
              parameters: [{name: message, value: B}]
          - name: C
            dependencies: [A]
            template: echo
            arguments:
              parameters: [{name: message, value: C}]
          - name: D
            dependencies: [B, C]
            template: echo
            arguments:
              parameters: [{name: message, value: D}]