apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-workflow-test
spec:
  entrypoint: test
  arguments:
    parameters:
      - name: message
        value: Message string default value
  templates:
    - name: test
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:3.12
        command: ["sh", "-c"]
        args: ["echo test1"]
