kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: master-cluster  # 主集群
nodes:
  - role: control-plane
    image: kindest/node:v1.24.15
    extraPortMappings:
      - containerPort: 6443   # 容器端口
        hostPort: 36443       # 主机端口
        protocol: tcp
      - containerPort: 31443  # 容器端口 karmada 端口
        hostPort: 31443       # 主机端口
        protocol: tcp
      - containerPort: 30009
        hostPort: 30009
        protocol: tcp
    extraMounts:
      - hostPath: /root/kind/node1-1
        containerPath: /files
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"  # 自定义 pod IP 地址范围
  serviceSubnet: "10.96.0.0/12"
  kubeProxyMode: "ipvs"
