# 定义两个任务
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  # 一个 pod(task) 中可以共享的参数
  params:
    - name: username
      type: string
  # 每个 step 都是一个 container
  steps:
    - name: goodbye
      image: alpine
      script: |
        #!/bin/bash
        echo "Goodbye $(params.username)!"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  params:
    - name: username
      type: string
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo "Hello $(params.username)"